Raise errors for inputs that would cause blank outputs
Imageomics/sum-buddy pull request #16
Opened 2024-07-26 13:58 UTC by thompsonmj

Addresses #14

2024-07-26 20:58 UTC, thompsonmj commented
@zoeduan I made some significant changes to `test_hasher.py` to have parameterize over all test checksums provided in `checksums` with `pytest.mark.parametrize`. It does this for default length settings as well as both with and without a `length` used for BLAKEs. I think this is a helpful reduction of repetition. 

@egrace479 I made it so that if an algorithm is not available on the system, it continues through the loop, skipping the subtest. There's also a test to make sure that if non-guaranteed algs are unavailable, just those that are available are tested.

2024-07-26 21:19 UTC, thompsonmj commented
Note that I tested possible failure modes of the testing approach locally by artificially perturbing available and guaranteed sets, e.g.:
```
def is_algorithm_available(algorithm):
    return algorithm in hashlib.algorithms_guaranteed # Only say that an algorithm is available if it's in the guaranteed set
```
Or by removing or writing an error for one or more entries in `checksums` causes tests to fail in the correct places.

2024-07-26 21:25 UTC, thompsonmj commented on tests/test_hasher.py
> +        pytest.skip(f"{algorithm} not available on system and not guaranteed.")
This skips the test for an algorithm parameterized with `parametrize` in a case like what was discovered with `ripemd160` on the GitHub Actions environment due to some algorithms being made unavailable by OpenSSL by default (as mentioned [here](https://github.com/Imageomics/sum-buddy/pull/15#issue-2430725466)).

2024-07-26 21:46 UTC, egrace479 requested changes

2024-07-26 21:46 UTC, egrace479 commented on src/sumbuddy/__main__.py
> +        sys.exit(str(e))
```suggestion
        sys.exit(str(e))


```
Just readability

2024-07-26 21:46 UTC, egrace479 commented on src/sumbuddy/exceptions.py
> +        super().__init__(message)
```suggestion
        super().__init__(message)

```

2024-07-26 21:46 UTC, egrace479 commented on src/sumbuddy/exceptions.py
> +    def __init__(selfe, input_directory):
```suggestion
    def __init__(self, input_directory):
```

2024-07-26 23:51 UTC, zoeduan reviewed
I run the test files below: 
1. test.filter.py - all passed
2. test_getChecksums.py - all passed
3. test_mappper.py - all passed
4. test_hasher.py - please refer to log below.
collected 42 items                                                                                                                                                           

test_hasher.py .................................sssss....                                                                                                              [100%]

======================================================================= 37 passed, 5 skipped in 0.04s

2024-07-27 14:21 UTC, zoeduan approved these changes

2024-07-29 15:34 UTC, egrace479 commented on tests/test_hasher.py
> +    test_all_algorithms_with_defaults(temp_file, algorithm)
```suggestion
    '''
    Run algorithm tests as if those that are not guaranteed are unavailable in the system.
    Skips are expected, but each algorithm should only be skipped once unless it is actually unavailable on the system running the testing.
    '''
    test_all_algorithms_with_defaults(temp_file, algorithm)
```

2024-07-29 15:35 UTC, egrace479 approved these changes

2024-07-29 15:51 UTC, merged