Accept a single file as input
Imageomics/sum-buddy pull request #19
Opened 2024-07-29 18:19 UTC by thompsonmj

Addresses #13

2024-07-29 18:56 UTC, thompsonmj commented on src/sumbuddy/__main__.py
> +            sys.exit(str(e))
The addition of this `isfile` condition block is all that's needed for core functionality of this PR.

2024-07-29 18:59 UTC, thompsonmj commented on src/sumbuddy/mapper.py
> +            raise NotADirectoryError(input_directory)
It makes more sense to me to raise an error if `gather_file_paths` receives a single file as an input than to repeat its path as an output. This doesn't interfere with use of the CLI or `get_checksums` method with a single file input.

2024-07-30 15:26 UTC, zoeduan reviewed
I run the tests, and please refer to below results:

collected 69 items                                                                                                                                                                      

tests/test_filter.py .............                                                                                                                                                [ 18%]
tests/test_getChecksums.py .........                                                                                                                                              [ 31%]
tests/test_hasher.py .................................sssss....                                                                                                                   [ 92%]
tests/test_mapper.py .....                                                                                                                                                        [100%]

============================================================================= 64 passed, 5 skipped in 0.10s

2024-07-30 15:36 UTC, zoeduan commented
LGTM!

2024-07-30 16:37 UTC, zoeduan approved these changes

2024-07-30 17:20 UTC, egrace479 requested changes

2024-07-30 17:52 UTC, egrace479 approved these changes

2024-07-30 18:59 UTC, merged